# Get all books
GET http://localhost:3000/books
###
# Get a single book
GET http://localhost:3000/books/BOOK_ID_HERE
###
# Create a new book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Pride and Prejudice",
  "author": "Jane Austen",
  "genre": "Classic",
  "rating": 5,
  "review": "One of my favorites!",
  "userId": "6869a4654a3bbe42883c6abd",
  "date": "07-05-2025"
}
###
# Update a book
PUT http://localhost:3000/books/6869a60ebb7b8f987038edfe
Content-Type: application/json

{
  "title": "The Hunger Games",
  "author": "Suzanne Collins",
  "genre": "Dystopian",
  "rating": 3,
  "review": "A gripping tale of survival!",
  "userId": "6869a4654a3bbe42883c6abd",
  "date": "2025-07-06"
}
###
# Delete a book
DELETE http://localhost:3000/books/6876c872c1beedf377b4a42c

# RENDER LINKS BELOW

# Get all books (Render)
GET https://cse341-project2-rr2b.onrender.com/books
###
# Get a single book (Render)
GET https://cse341-project2-rr2b.onrender.com/books/BOOK_ID_HERE
###
# Create a new book (Render)
POST https://cse341-project2-rr2b.onrender.com/books
Content-Type: application/json

{
  "title": "Boys in the Boat",
  "author": "Daniel James Brown",
  "genre": "Non-Fiction",
  "rating": 4,
  "review": "Decent book!",
  "userId": "6869a4654a3bbe42883c6abd",
  "date": "07-05-2025"
}
###
# Update a book (Render)
PUT https://cse341-project2-rr2b.onrender.com/books/6869a60ebb7b8f987038edfe
Content-Type: application/json

{
  "title": "The Hunger Games",
  "author": "Suzanne Collins",
  "genre": "Dystopian",
  "rating": 4,
  "review": "A gripping tale of survival!",
  "userId": "6869a4654a3bbe42883c6abd",
  "date": "2025-07-06"
}
###
# Delete a book (Render)
DELETE https://cse341-project2-rr2b.onrender.com/books/686d471c97c304fa1661220a